### ISSUE TITLE
Cannot authenticate.

### ISSUE THREAD

**Issue by ggendel** [danielfernau/unifi-protect-video-downloader#106]
If I pass in a bad username/password I get a 401 error, but when I pass it the correct username/password I get this 499 error so I'm sure that I've gotten passed the initial authentication.  Do I need to disable 2FA for this to work?  Would it be possible to add 2FA support?

`% docker run -v /path/on/host/machine:/downloads unifitoolbox/protect-archiver download --address 192.168.1.1 --password <pw> --username <name> .
Getting camera list
Authentication failed with status code 499! Check username and password.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/download.py", line 202, in download
    camera_list = client.get_camera_list()
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/client/__init__.py", line 85, in get_camera_list
    return Downloader.get_camera_list(self.session, connected)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/downloader/__init__.py", line 33, in get_camera_list
    return get_camera_list(session, connected)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/downloader/get_camera_list.py", line 18, in get_camera_list
    cookies={"TOKEN": session.get_api_token()},
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/client/unifi_os.py", line 61, in get_api_token
    self._api_token = self.fetch_session_cookie_token()
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/client/unifi_os.py", line 47, in fetch_session_cookie_token
    raise Errors.ProtectError(2)
TypeError: 'Exception' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/protect-archiver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/__init__.py", line 21, in main
    cli.main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/download.py", line 229, in download
    except Errors.ProtectError as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
`

**Comment by danielfernau** [comment]
Hi @ggendel 
You need to add a local user first, as described here: https://github.com/danielfernau/unifi-protect-video-downloader/wiki/Basic-Usage#general

Using your main (cloud) admin account is neither recommended nor supported. For security reasons you should always create individual, local accounts with only the necessary permissions for each external application you're using with your UDM(-Pro).
