### ISSUE TITLE
Docker image breaks on run

### ISSUE THREAD

**Issue by nyanchor** [danielfernau/unifi-protect-video-downloader#128]
There seems to be a bug in the docker image build
```bash
ile "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
     conn = connection.create_connection(
   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
     raise err
   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
     sock.connect(sa)
 ConnectionRefusedError: [Errno 111] Connection refused
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
     httplib_response = self._make_request(
   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
     self._validate_conn(conn)
   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
     conn.connect()
   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
     self.sock = conn = self._new_conn()
   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
     raise NewConnectionError(
 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5c19ad6310>: Failed to establish a new connection: [Errno 111] Connection refused
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
     resp = conn.urlopen(
   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
     retries = retries.increment(
   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
     raise MaxRetryError(_pool, url, error or ResponseError(cause))
 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /api/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5c19ad6310>: Failed to establish a new connection: [Errno 111] Connection refused'))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/download.py", line 202, in download
     camera_list = client.get_camera_list()
   File "/usr/local/lib/python3.8/site-packages/protect_archiver/client/__init__.py", line 85, in get_camera_list
     return Downloader.get_camera_list(self.session, connected)
   File "/usr/local/lib/python3.8/site-packages/protect_archiver/downloader/__init__.py", line 33, in get_camera_list
     return get_camera_list(session, connected)
   File "/usr/local/lib/python3.8/site-packages/protect_archiver/downloader/get_camera_list.py", line 18, in get_camera_list
     cookies={"TOKEN": session.get_api_token()},
   File "/usr/local/lib/python3.8/site-packages/protect_archiver/client/unifi_os.py", line 61, in get_api_token
[[0;32m  OK  [0m] Started [0;1;39msnap.google-cloud-…-4b19-baa5-55135f1cdb7e.scope[0m.
     self._api_token = self.fetch_session_cookie_token()
   File "/usr/local/lib/python3.8/site-packages/protect_archiver/client/unifi_os.py", line 36, in fetch_session_cookie_token
     response = requests.post(
   File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 117, in post
     return request('post', url, data=data, json=json, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
     return session.request(method=method, url=url, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
     r = adapter.send(request, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
     raise ConnectionError(e, request=request)
 requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /api/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5c19ad6310>: Failed to establish a new connection: [Errno 111] Connection refused'))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/bin/protect-archiver", line 8, in <module>
     sys.exit(main())
   File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/__init__.py", line 21, in main
     cli.main()
   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
     rv = self.invoke(ctx)
   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
     return _process_result(sub_ctx.command.invoke(sub_ctx))
   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
     return ctx.invoke(self.callback, **ctx.params)
   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
     return __callback(*args, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/download.py", line 229, in download
     except Errors.ProtectError as e:
 TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by danielfernau** [comment]
Thanks for the heads-up. Just verified that downloads work with both the current `edge` tag (SHA [f650cc6d96cf](https://hub.docker.com/layers/unifitoolbox/protect-archiver/edge/images/sha256-f650cc6d96cfa7d233911162825729c2e6457c7e15801e9b97aaaafce2bd6e7f?context=explore)) as well as the `2.1.2` tag -- no issues across three Docker hosts (2 servers, 1 desktop) in combination with an UDMP as well as an UNVR. So the latest images seem fine...

The error messages `ConnectionRefusedError: [Errno 111] Connection refused` and `urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded` look like that there's either an issue with the access to port 443 (if run locally on UDMP/UNVR) or that you need to add/change the `--address` parameter (if run from another machine on the network). You can also try deleting the Docker images locally and re-downloading them afterwards.

Feel free to reach out again in case this doesn't solve the problem or you need additional help!
