### ISSUE TITLE
Error on sync: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by DrMarlin** [danielfernau/unifi-protect-video-downloader#252]
I'm experiencing the following error when I'm attempting to synchronize with my UNVR (Protect 2.7.9). I'd welcome any advice/guidance as I'm stumped. Thank you!

Here's my CMD:
sync --address X.X.X.X --port 443 --username USERNAME --password PASSWORD /downloads

Log:
`Getting camera list
Successfully retrieved data from https://X.X.X.X:443/proxy/protect/api/cameras
Cameras found:
- Front Street (634777dd039bd503e70003ff)
- Backyard Garage (634777dd0354d503e70003fc)
- Inside Storage Room (634777dd036fd503e70003fd)
- Front Driveway (634777dd02a7d503e70003f9)
- Back Deck (634777dd0207d503e70003f5)
- Inside Den (634777dd0263d503e70003f7)
- Backyard Gazebo (634777dd02eed503e70003fa)
- Backyard West (634777dd0386d503e70003fe)
- Backyard Shed (634777dd01b0d503e70003f3)
- Front Door (634777dd0339d503e70003fb)
- Inside Living Room (634777dd03b1d503e7000400)
- Inside Office (634777dd028ad503e70003f8)
- Inside Family Room (634777dd01e5d503e70003f4)
- Backyard East (634777dd0229d503e70003f6)
Synchronizing video files from 'https://X.X.X.X:443
Traceback (most recent call last):
  File "/usr/local/bin/protect-archiver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/__init__.py", line 21, in main
    cli.main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/sync.py", line 131, in sync
    process.run(camera_list, ignore_state=ignore_state)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/sync.py", line 40, in run
    state = self.readstate()
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/sync.py", line 23, in readstate
    state = json.load(fp)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by danielfernau** [comment]
Hi @DrMarlin - thanks for reporting. I'll have a look at it as soon as possible. Does this happen every time or just sometimes on your machine? Looks like either an invalid request/response or might be related to an API change with the new version...

**Comment by DrMarlin** [comment]
Every time now unfortunately. Thank you for investigating!
