### ISSUE TITLE
Login Successful, Error Downloading

### ISSUE THREAD

**Issue by SaavageBueno** [danielfernau/unifi-protect-video-downloader#281]
docker run -v /home/madison/downloads unifitoolbox/protect-archiver download --address 172.16.0.1 --username saavagebueno --password ********  --use-subfolders /downloads
Getting camera list
Successfully retrieved data from https://172.16.0.1:443/proxy/protect/api/cameras
Cameras found:
- Backyard (632ba56a03dff40387000f1b)
- G3 Instant (63ae2d3e01dbd7038700bac8)
- 325 Front Door (62f197bd0280260387000e8d)
Downloading video files between None and None from 'https://172.16.0.1:443/proxy/protect/api/video/export' for camera Backyard
Downloading footage for camera 'Backyard' (632ba56a03dff40387000f1b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/download.py", line 227, in download
    Downloader.download_footage(client, start, end, camera)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/downloader/__init__.py", line 47, in download_footage
    return download_footage(client, start, end, camera)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/downloader/download_footage.py", line 23, in download_footage
    for interval_start, interval_end in calculate_intervals(start, end):
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/utils.py", line 52, in calculate_intervals
    start_diff_to_next_full_hour = diff_round_up_to_full_hour(start) - start
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/utils.py", line 21, in diff_round_up_to_full_hour
    if date_time_object.minute != 0 or date_time_object.second != 0:
AttributeError: 'NoneType' object has no attribute 'minute'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/protect-archiver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/__init__.py", line 21, in main
    cli.main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/download.py", line 238, in download
    except Errors.ProtectError as e:
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by jforeman** [comment]
Seeing the same behavior. Protect 5.0.51.

Available to debug.

**Comment by danielfernau** [comment]
Hey y'all, thanks for reporting. I'll look into this as soon as I can. 

@jforeman - Thanks for offering to test/debug! Will let you know if I need any additional data 👍
