### ISSUE TITLE
Cannot authenticate with CloudKey Gen2

### ISSUE THREAD

**Issue by AltergeistGG** [danielfernau/unifi-protect-video-downloader#469]
Is unifi-protect-video-downloader compatible with UniFi OS v4.0.6?  I am trying to download videos from a CloudKey Gen2 but I cannot get past this error:

```
$ docker run -v /home/win4ever:/downloads unifitoolbox/protect-archiver download --address=192.168.1.30 --username="username" --password="password" --start "2024-06-09 20:00:00" --end "2024-06-09 21:00:00" /downloads

Getting camera list
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/download.py", line 274, in download
    camera_list = client.get_camera_list()
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/client/__init__.py", line 87, in get_camera_list
    return Downloader.get_camera_list(self.session)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/downloader/__init__.py", line 33, in get_camera_listv
    return get_camera_list(session)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/downloader/get_camera_list.py", line 19, in get_camera_list
    cookies={"TOKEN": session.get_api_token()},
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/client/unifi_os.py", line 61, in get_api_token
    self._api_token = self.fetch_session_cookie_token()
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/client/unifi_os.py", line 53, in fetch_session_cookie_token
    assert session_cookie_token
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/protect-archiver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/__init__.py", line 21, in main
    cli.main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/cli/download.py", line 303, in download
    except Errors.ProtectError as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by danielfernau** [comment]
Hi there and sorry for the late reply! Yes, should be compatible. However, this application is currently not being actively developed due to lack of time, the last few months only covered dependency maintenance. Will probably re-write it from scratch soon anyways :)

Your logs, however, seem to point at an issue with the session cookie obtained from the UniFi Console. I'd have to replicate this scenario to tell you exactly what's happening there.

Will keep this issue open for now; new version coming as soon as I find the time to work on it.

Thanks!
