### ISSUE TITLE
Active motion events cause motion_event["end"] to be NoneType in get_motion_events_list.py

### ISSUE THREAD

**Issue by JimReprogle** [danielfernau/unifi-protect-video-downloader#65]
Ran into an odd, albeit infrequent scenario. It appears that a motion event that is still ongoing triggers a latent bug in get_motion_event_list.py on line 34. In the test scenario, there was a camera that had a flag waving in its field of view. Therefore the value of ```motion_event["end"]``` was ```"None"``` because the motion event had not ended yet. To test this scenario, I added a conditional to get_motion_event_list.py at line 30.

Stack trace here:
```
Successfully retrieved data from https://192.168.1.1:443/proxy/protect/api/events?type=motion&start=1631768400000&end=1631912657000
Traceback (most recent call last):
  File "/Users/UserName/scripts/unifi-protect-video-downloader/protect_archiver/cli/events.py", line 183, in events
    motion_event_list = client.get_motion_event_list(start, end, camera_list)
  File "/Users/UserName/scripts/unifi-protect-video-downloader/protect_archiver/client/__init__.py", line 79, in get_motion_event_list
    return Downloader.get_motion_event_list(self.session, start, end, camera_list)
  File "/Users/UserName/scripts/unifi-protect-video-downloader/protect_archiver/downloader/__init__.py", line 33, in get_motion_event_list
    return get_motion_event_list(session, start, end, camera_list)
  File "/Users/UserName/scripts/unifi-protect-video-downloader/protect_archiver/downloader/get_motion_event_list.py", line 35, in get_motion_event_list
    end=datetime.fromtimestamp(motion_event["end"] / 1000),
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/UserName/scripts/unifi-protect-video-downloader/protect_archiver/cli/__init__.py", line 20, in main
    cli.main()
  File "/Users/UserName/Library/Caches/pypoetry/virtualenvs/protect-archiver-AsGvsaa6-py3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/UserName/Library/Caches/pypoetry/virtualenvs/protect-archiver-AsGvsaa6-py3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/UserName/Library/Caches/pypoetry/virtualenvs/protect-archiver-AsGvsaa6-py3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/UserName/Library/Caches/pypoetry/virtualenvs/protect-archiver-AsGvsaa6-py3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/UserName/scripts/unifi-protect-video-downloader/protect_archiver/cli/events.py", line 226, in events
    except Errors.ProtectError as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

To reproduce the issue:
```
START=`date -v -1d +'%Y-%m-%d'`
END=`date +'%Y-%m-%dT%H:%M:%S'`
poetry run protect-archiver events --address <IP ADDR> --start $START --end $END /Users/UserName/Downloads
```

Code snippet to test fix:
```
    motion_event_list = []
    for motion_event in motion_events:
        if not (motion_event["end"] is None):
            motion_event_list.append(
                MotionEvent(
                    id=motion_event["id"],
                    start=datetime.fromtimestamp(motion_event["start"] / 1000),
                    end=datetime.fromtimestamp(motion_event["end"] / 1000),
                    camera_id=motion_event["camera"],
                    score=motion_event["score"],
                    thumbnail_id=motion_event["thumbnail"],
                    heatmap_id=motion_event["heatmap"],
                )
            )
```

I'm not sure if there is a better way to do this. Perhaps removing the flag from the camera's field of view would suffice.

https://github.com/unifi-toolbox/unifi-protect-video-downloader/blob/c06000e9e2d423651ce73c0669dca06056a6ba14/protect_archiver/downloader/get_motion_event_list.py#L34

**Comment by L3o-pold** [comment]
@danielfernau do you need help on this?

**Comment by danielfernau** [comment]
@L3o-pold Help is always welcome if you have some time to spare. My current work schedule doesn't allow for much maintenance on the project anymore but I also don't want to abandon it.

I've just created a pull request draft at https://github.com/danielfernau/unifi-protect-video-downloader/pull/114 which includes the suggested piece of code from the original issue comment. If you want to do some testing to confirm it works as expected it would help a lot. 

Thanks!

**Comment by danielfernau** [comment]
@JimReprogle Fix will be part of next release. Sorry for the long wait.
